### ISSUE TITLE
Unsupported callback API version

### ISSUE THREAD

**Issue by r0b3rt74** [andrea-mattioli/bticino_x8000_component#24]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [documentation](https://github.com/andrea-mattioli/bticino_x8000_component/blob/main/README.md)
- [X] I have installed the latest version

### The problem

Not possible to get thermostat values

### Diagnostics information

This is from the log

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[23:44:24] INFO: Smarter file already exist and contain some data.
[23:44:24] INFO: Setup config file...
 * Serving Flask app 'bticino'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5588
 * Running on http://172.30.33.6:5588
Press CTRL+C to quit
Traceback (most recent call last):
  File "/hassio_bticino_smarter/mqtt.py", line 36, in <module>
    client = mqtt.Client("Bticino_X8000")  
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/paho/mqtt/client.py", line 772, in __init__
    raise ValueError(
ValueError: Unsupported callback API version: version 2.0 added a callback_api_version, see docs/migrations.rst for details

**Comment by andrea-mattioli** [comment]
Not related to this component. I don't use mqtt!
