### ISSUE TITLE
Updating HACS 2.0.1 - No longer working!

### ISSUE THREAD

**Issue by engal89** [andrea-mattioli/bticino_x8000_component#31]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [documentation](https://github.com/andrea-mattioli/bticino_x8000_component/blob/main/README.md)
- [X] I have installed the latest version

### The problem

After installing HACS 2.0.1 i have this error:

Error setting up entry Bticino X8000 for bticino_x8000
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bticino_x8000/__init__.py", line 65, in async_setup_entry
    subscription_id = await add_c2c_subscription(plant_id, webhook_id)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bticino_x8000/__init__.py", line 36, in add_c2c_subscription
    response = await bticino_api.set_subscribe_c2c_notifications(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bticino_x8000/api.py", line 328, in set_subscribe_c2c_notifications
    return {"status_code": status_code, "text": json.loads(content)}
                                                ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Diagnostics information

Error setting up entry Bticino X8000 for bticino_x8000
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bticino_x8000/__init__.py", line 65, in async_setup_entry
    subscription_id = await add_c2c_subscription(plant_id, webhook_id)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bticino_x8000/__init__.py", line 36, in add_c2c_subscription
    response = await bticino_api.set_subscribe_c2c_notifications(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bticino_x8000/api.py", line 328, in set_subscribe_c2c_notifications
    return {"status_code": status_code, "text": json.loads(content)}
                                                ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by engal89** [comment]
I also try to delete and re-add the thermostat and i have this error:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bticino_x8000/__init__.py", line 65, in async_setup_entry
    subscription_id = await add_c2c_subscription(plant_id, webhook_id)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bticino_x8000/__init__.py", line 36, in add_c2c_subscription
    response = await bticino_api.set_subscribe_c2c_notifications(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bticino_x8000/api.py", line 315, in set_subscribe_c2c_notifications
    async with session.post(
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1353, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 684, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 999, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 640, in read
    await self._waiter
asyncio.exceptions.CancelledError


Before updating HACS all works correct.
Thanks

**Comment by engal89** [comment]
I was investigating too and seems exactly this. Thanks for your answer. I close the issue hoping they will resume the service soon. Thank you!
