### ISSUE TITLE
update_token

### ISSUE THREAD

**Issue by onofalt** [andrea-mattioli/bticino_x8000_component#38]
### Checks

- [X] I checked Legrand API works properly [c2c](https://portal.developer.legrand.com/reference#api=smartherV2&operation=Get-subscriptions-to-C2C-notifications) and [Plants](https://portal.developer.legrand.com/reference#api=smartherV2&operation=Plants)
- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [documentation](https://github.com/andrea-mattioli/bticino_x8000_component/blob/main/README.md)
- [X] I have installed the latest version

### The problem

The component not receive callback from legrand.
I've check connection from legrand netherland server.

i found this exeption in log.

### Diagnostics information

2024-11-15 19:21:02.136 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/bticino_x8000/__init__.py", line 55, in update_token
    hass.config_entries.async_update_entry(config_entry, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1969, in async_update_entry
    raise UnknownEntry(entry.entry_id)
homeassistant.config_entries.UnknownEntry: d1ec39f5a8a78aec8a637348414334f0

**Comment by onofalt** [comment]
@andrea-mattioli  riesci a guidarmi nella risoluzione ? grazie
